# Generated by Django 4.0.4 on 2022-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_parent_comment_parents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя автора'),
        ),
    ]
